redis:
  image: redis
  ports:
    - "6379:6379"
mongo:
    image: mongo:latest
    ports:
        - "27017:27017"
storm:
  build: .
  command: sparse run
  volumes:
   - .:/code
  links:
   - redis
   - mongo